import { StyleSheet } from "react-native";

const ProfileTemplateStyle = StyleSheet.create({
  parentContainer: {
    flex: 1,
    backgroundColor: "black",
  },
  discriptionContainer: {
    flexDirection: "row",
    marginTop: 22,
  },
  imageContainer: {
    marginTop: 10,
    alignItems: "flex-start",
  },
  image: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  titleName: {
    color: "#C1C1C1",
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 16,
    fontFamily: "Reddit Sans",
  },
  titlePhone: {
    marginTop: 8,
    color: "#C1C1C1",
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 16,
    fontFamily: "Reddit Sans",
  },
  titleEmail: {
    marginTop: 8,
    color: "#C1C1C1",
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 16,
    fontFamily: "Reddit Sans",
  },
  tagsContainer: {
    marginTop: 14,
    paddingHorizontal: 16,
    paddingBottom: 16,
    paddingTop: 16,
    backgroundColor: "#262626",
  },
  messageHeading: {
    lineHeight: 16,
    paddingLeft: 6,
    color: "#E8E8E8",
    fontSize: 16,
    fontFamily: "Reddit Sans",
    fontWeight: "600",
  },
  tagsHeadingText: {
    paddingLeft: 8,
    fontSize: 16,
    color: "#E8E8E8",
    lineHeight: 16,
    fontWeight: "600",
    fontFamily: "Reddit Sans",
  },
  messageHeadingText: {
    paddingLeft: 6,
    fontSize: 16,
    color: "#E8E8E8",
    fontWeight: "600",
    fontFamily: "Reddit Sans",
  },
  hashtag: {
    flexDirection: "row",
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: "#353535",
    marginHorizontal: 8,
    marginVertical: 8,
    borderRadius: 24,
  },
  profileHashtags: {
    flexDirection: "row",
    paddingHorizontal: 8,
    paddingTop: 2,
    backgroundColor: "#353535",
    marginHorizontal: 8,
    marginVertical: 8,
    borderRadius: 24,
  },
  profileMessageContainer: {
    marginTop: 14,
    paddingTop: 16,
    paddingBottom: 20,
    paddingHorizontal: 16,
    backgroundColor: "#262626",
  },
  messageHeadingContainer: {
    justifyContent: "space-between",
    flexDirection: "row",
  },
  messageDotsContainer: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 20,
    marginBottom: 3,
  },
  messageContainer: {
    marginTop: 14,
    paddingBottom: 20,
    paddingHorizontal: 16,
    backgroundColor: "#262626",
  },
  messageTitle: {
    marginTop: 8,
    fontSize: 15,
    color: "#E8E8E8",
    marginLeft: 22,
    fontWeight: "bold",
    textDecorationLine: "underline",
  },
  messageText: {
    marginLeft: 10,
    fontSize: 14,
    color: "#E8E8E8",
    marginTop: 5,
    flexWrap: "wrap",
  },
  manageProfileContainer: {
    backgroundColor: "#262626",
    paddingTop: 44,
    paddingBottom: 30,
    paddingHorizontal: 16,
  },
  manageHeadingContainer: {
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  backIcon: {
    color: "#E8E8E8",
    marginTop: -2,
  },
  myProfileText: {
    color: "#E8E8E8",
    fontSize: 18,
    fontWeight: "600",
    lineHeight: 18,
    paddingLeft: 8,
    marginTop: 2,
  },
  editText: {
    marginTop: 2,
    fontWeight: "400",
    fontSize: 14,
    color: "#E8E8E8",
  },
  displayUserDetailsContainer: {
    flex: 1,
    marginTop: 4,
    marginLeft: 10,
  },
  manageProfileIconContainer: {
    marginRight: 16,
    justifyContent: "space-between",
  },
  tagsHeadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  addIconContainer: {
    paddingBottom: 10,
    alignItems: "flex-end",
    paddingRight: 8,
  },
  tagsContent: {
    color: "#E8E8E8",
    fontWeight: "400",
    fontFamily: "Reddit Sans",
    fontSize: 14,
  },
  crossIcon: {
    paddingTop: 4,
    paddingLeft: 4,
    paddingBottom: 4,
    color: "#7A7776",
  },
});
export default ProfileTemplateStyle;
