import { StyleSheet } from "react-native";

const ManageProfileStyle = StyleSheet.create({
  userProfileContainer: {
    flex: 1,
  },
  editProfileHeadingContainer: {
    height: 110,
  },
  profileHeading: {
    textAlign: "center",
    marginTop: 30,
    fontSize: 16,
    fontWeight: "600",
    color: "#E8E8E8",
    lineHeight: 18,
  },
  displayImageContainer: {
    alignItems: "center",
    marginTop: -44,
  },
  imageContainer: {
    borderRadius: 40,
    borderWidth: 2,
    borderColor: "#FFFFFF",
  },
  image: {
    width: 80,
    height: 80,
    borderRadius: 40,
  },
  manageProfileHeader: {
    marginTop: 20,
    justifyContent: "space-between",
    flexDirection: "row",
    marginHorizontal: 18,
  },
  personalDetailsHeading: {
    fontSize: 14,
    color: "#E8E8E8",
    lineHeight: 16,
    fontWeight: "600",
  },
  userProfileDetailsContainer: {
    marginHorizontal: 16,
  },
  qrCodeText: {
    fontWeight: "600",
    fontSize: 15,
    lineHeight: 16,
    color: "#E8E8E8",
  },
  myQrCodeContainer: {
    flexDirection: "row",
    marginTop: 12,
    justifyContent: "center",
  },
  qrIcon: {
    marginLeft: 8,
    marginTop: -5,
  },
  toggleBtnContainer: {
    flexDirection: "row",
    marginTop: 16,
    backgroundColor: "#353535",
    alignItems: "center",
    alignSelf: "center",
    borderRadius: 100,
    padding: 4,
  },
  linkedinText: {
    fontSize: 14,
    lineHeight: 18,
    fontWeight: "400",
    color: "#1C1C1C",
    paddingVertical: 4,
    paddingHorizontal: 16,
  },
  cardDetailsBtn: {
    marginVertical: 4,
    marginHorizontal: 4,
    backgroundColor: "#262626",
    borderRadius: 100,
  },
  editImgIcon: {
    height: 24,
    width: 24,
    zIndex: 1,
    marginTop: -32,
    marginLeft: 70,
  },
  titleName: {
    marginTop: 12,
    fontSize: 16,
    color: "#E8E8E8",
    fontWeight: "600",
    lineHeight: 16,
  },
  nameContainer: {
    flexDirection: "row",
    justifyContent: "flex-start",
    paddingHorizontal: 20,
    marginTop: 20,
    paddingBottom: 8,
  },
  userName: {
    color: "#2b4d66",
    fontSize: 18,
    fontWeight: "600",
  },
  nameInput: {
    marginTop: -6,
    color: "grey",
    fontSize: 15,
    fontWeight: "600",
    width: 300,
  },
  qrContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    // paddingHorizontal: 20,
    paddingVertical: 20,
    backgroundColor: "#eef8f9",
    borderBottomWidth: 2,
    borderTopWidth: 2,
    borderColor: "#3e6c8f",
  },
  qrLinking: {
    marginLeft: 50,
  },
  qrLinkingText: {
    marginTop: 5,
    marginLeft: -25,
    fontSize: 15,
    color: "#44585b",
  },
  qrCardDetails: {
    marginRight: 40,
  },
  qrCardDetailsText: {
    marginTop: 5,
    marginLeft: -48,
    fontSize: 15,
    color: "#44585b",
  },
  updateBtnContainer: {
    alignItems: "center",
    marginVertical: 40,
    marginHorizontal: 20,
    backgroundColor: "#89FFB8",
    borderRadius: 54,
  },
  updateBtnText: {
    color: "#222222",
    paddingVertical: 12,
    fontSize: 14,
    fontWeight: "400",
    lineHeight: 16,
  },
  toastContainer: {
    backgroundColor: "#4CAF50",
    borderWidth: 1,
    borderColor: "#FFF",
    borderRadius: 10,
    padding: 10,
  },
  toastText: {
    color: "#FFF",
    fontSize: 16,
    fontWeight: "bold",
  },
  linkedinBtn: {
    marginVertical: 4,
    marginHorizontal: 4,
    backgroundColor: "#84FFB5",
    borderRadius: 100,
  },
  cardDetailsText: {
    fontSize: 15,
    lineHeight: 18,
    fontWeight: "400",
    paddingVertical: 4,
    color: "#747474",
    paddingHorizontal: 12,
  },
  scanContainer: {
    marginTop: 20,
    alignSelf: "center",
  },
  scanImgContainer: {
    alignSelf: "center",
    height: 260,
    width: 280,
    borderRadius: 10,
  },
  updateQrText: {
    fontSize: 16,
    fontWeight: "600",
    lineHeight: 16,
    marginTop: 18,
    color: "#747474",
    alignSelf: "center",
    textDecorationLine: "underline",
  },
  qrCodeContainer: {
    marginTop: 24,
  },
});
export default ManageProfileStyle;
